Plugins/NopStation.Plugin.Misc.SalesForecasting/Models/SalesPrediction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NopStation.Plugin.Misc.SalesForecasting.Models
{

    public class SalesRegressionPrediction
    {
        // Below columns are produced by the model's predictor.
        public float Score { get; set; }
    }

    public class WeeklySalesTimeSeriesPrediction
    {
        public float[] ForecastedWeeklySalesUnits { get; set; }

        public float[] ConfidenceLowerBound { get; set; }

        public float[] ConfidenceUpperBound { get; set; }
    }
}

Plugins/NopStation.Plugin.Misc.SalesForecasting/Areas/Admin/Controllers/SalesForecastingController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.EMMA;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Nop.Core;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using NopStation.Plugin.Misc.Core.Controllers;
using NopStation.Plugin.Misc.Core.Filters;
using NopStation.Plugin.Misc.SalesForecasting.Areas.Admin.Factories;
using NopStation.Plugin.Misc.SalesForecasting.Areas.Admin.Models;
using NopStation.Plugin.Misc.SalesForecasting.Extensions;
using NopStation.Plugin.Misc.SalesForecasting.Services;

namespace NopStation.Plugin.Misc.SalesForecasting.Areas.Admin.Controllers
{
    public class SalesForecastingController : NopStationAdminController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly ISalesForecastingService _salesForecastingService;
        private readonly IProductService _productService;
        private readonly ISalesForecastingModelFactory _salesForecastingModelFactory;

        #endregion

        #region Ctor

        public SalesForecastingController(ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext,
            ISalesForecastingService salesForecastingService,
            IProductService productService,
            ISalesForecastingModelFactory salesForecastingModelFactory)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
            _salesForecastingService = salesForecastingService;
            _productService = productService;
            _salesForecastingModelFactory = salesForecastingModelFactory;
        }

        #endregion

        #region Methods

        #region Configure
        
        public async Task<IActionResult> ConfigureAsync()
        {
            if (!await _permissionService.AuthorizeAsync(SalesForecastingProvider.ManageConfiguration))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var salesForcastingSettings = await _settingService.LoadSettingAsync<SalesForecastingSettings>(storeScope);

            var model = new ConfigurationModel
            {
                NumberofBestDemandProduct = salesForcastingSettings.NumberofBestDemandProduct,
                FridayIsWeekend = salesForcastingSettings.FridayIsWeekend,
                SaturdayIsWeekend = salesForcastingSettings.SaturdayIsWeekend, 
                SundayIsWeekend = salesForcastingSettings.SundayIsWeekend, 
                MondayIsWeekend = salesForcastingSettings.MondayIsWeekend, 
                TuesdayIsWeekend = salesForcastingSettings.TuesdayIsWeekend, 
                WednesdayIsWeekend = salesForcastingSettings.WednesdayIsWeekend, 
                ThursdayIsWeekend = salesForcastingSettings.ThursdayIsWeekend
            };

            if (storeScope > 0)
            {
                model.NumberofBestDemandProduct_OverrideForStore = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.NumberofBestDemandProduct, storeScope);
                model.FridayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.FridayIsWeekend, storeScope);
                model.SaturdayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.SaturdayIsWeekend, storeScope);
                model.SundayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.SundayIsWeekend, storeScope);
                model.MondayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.MondayIsWeekend, storeScope);
                model.TuesdayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.TuesdayIsWeekend, storeScope);
                model.WednesdayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.WednesdayIsWeekend, storeScope);
                model.ThursdayIsWeekend = await _settingService.SettingExistsAsync(salesForcastingSettings, x => x.ThursdayIsWeekend, storeScope);
            }

            return View(model);
        }

        [EditAccess, HttpPost]
        public async Task<IActionResult> ConfigureAsync(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(SalesForecastingProvider.ManageConfiguration))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await ConfigureAsync();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var salesForcastingSettings = await _settingService.LoadSettingAsync<SalesForecastingSettings>(storeScope);

            //save settings
            salesForcastingSettings.NumberofBestDemandProduct = model.NumberofBestDemandProduct;
            salesForcastingSettings.FridayIsWeekend = model.FridayIsWeekend;
            salesForcastingSettings.SaturdayIsWeekend = model.SaturdayIsWeekend;
            salesForcastingSettings.SundayIsWeekend = model.SundayIsWeekend;
            salesForcastingSettings.MondayIsWeekend = model.MondayIsWeekend;
            salesForcastingSettings.TuesdayIsWeekend = model.TuesdayIsWeekend;
            salesForcastingSettings.WednesdayIsWeekend = model.WednesdayIsWeekend;
            salesForcastingSettings.ThursdayIsWeekend = model.ThursdayIsWeekend;
            
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.NumberofBestDemandProduct, model.NumberofBestDemandProduct_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.FridayIsWeekend, model.FridayIsWeekend_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.SaturdayIsWeekend, model.SaturdayIsWeekend_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.SundayIsWeekend, model.SundayIsWeekend_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.MondayIsWeekend, model.MondayIsWeekend_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.TuesdayIsWeekend, model.TuesdayIsWeekend_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.WednesdayIsWeekend, model.WednesdayIsWeekend_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(salesForcastingSettings, x => x.ThursdayIsWeekend, model.ThursdayIsWeekend_OverrideForStore, storeScope, false);
            //now clear settings cache
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await ConfigureAsync();
        }
        #endregion

        #region Model
        [EditAccess, HttpPost]
        public async Task<IActionResult> TrainModelAsync()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProducts))
                return AccessDeniedView();

            bool largeDataSet = false;

            #region Model Directory Preparation
            _salesForecastingService.PathPreparation();
            #endregion

            #region Train Sales Prediction Time series Model
            var trainWeeklyTimeSeriesModelStatus = await _salesForecastingService.TrainWeeklySalesPredictionTimeSeriesModelAsync();

            if (trainWeeklyTimeSeriesModelStatus.Item1)
                _notificationService.SuccessNotification("Training of time series model successfull");
            else
                _notificationService.ErrorNotification("Training of time series model failed");
            #endregion

            #region Train Daily Product Sales Largre Dimension Model
            /// <summary>
            /// Use this model when the dataset is very big otherwise use 
            /// specific and low dimension models
            ///</summary>
            
            if(largeDataSet)
            {
                var trainWeeklyPrductSalesPredictionModelStatus = await _salesForecastingService.TrainLargeFeatureProductSalesPredictionModelAsync();

                if (trainWeeklyPrductSalesPredictionModelStatus.Item1)
                    _notificationService.SuccessNotification("Training of product sales prediction model successfull");
                else
                    _notificationService.ErrorNotification("Training of product sales prediction model failed");
            }

            #endregion

            #region Train Ensemble Learning Model

            if(!largeDataSet)
            {

Plugins/NopStation.Plugin.Misc.SalesForecasting/Areas/Admin/Views/SalesForecasting/Configure.cshtml
@model ConfigurationModel

@{
    ViewBag.PageTitle = T("Admin.SalesForecasting.Configure.PageTitle").Text;
    NopHtml.SetActiveMenuItemSystemName("SalesForecasting.Configuration");

    const string hideInfoBlockAttributeName = "SalesForcastingPage.HideInfoBlock";
    var customer = await workContext.GetCurrentCustomerAsync();
    var hideInfoBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideInfoBlockAttributeName);
}

<form asp-controller="SalesForecasting" asp-action="Configure" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.SalesForecasting.Configure.PageHead")
        </h1>

        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
        </div>

        <div class="float-right">
            <button type="button" name="Train" class="btn btn-primary" id="train-button-id">
                <i class="far fa-save"></i>
                @T("Admin.SalesForecasting.Configure.TrainModel")
            </button>
        </div>

    </div>
    <div asp-validation-summary="All"></div>
    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <nop-cards id="salesForcasting-cards">
                    <nop-card asp-name="store-regional-info" asp-icon="fas fa-info" asp-title="@T("Admin.SalesForecasting.Configure.StoreConfigure")" asp-hide-block-attribute-name="@hideInfoBlockAttributeName" asp-hide="@hideInfoBlock" asp-advanced="false">

                        <div class="card-body">
                            @await Component.InvokeAsync("StoreScopeConfiguration")
                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="SaturdayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="SaturdayIsWeekend" />
                                    <span asp-validation-for="SaturdayIsWeekend"></span>
                                </div>
                            </div>
                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="SundayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="SundayIsWeekend" />
                                    <span asp-validation-for="SundayIsWeekend"></span>
                                </div>
                            </div>

                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="MondayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="MondayIsWeekend" />
                                    <span asp-validation-for="MondayIsWeekend"></span>
                                </div>
                            </div>
                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="TuesdayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="TuesdayIsWeekend" />
                                    <span asp-validation-for="TuesdayIsWeekend"></span>
                                </div>
                            </div>
                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="WednesdayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="WednesdayIsWeekend" />
                                    <span asp-validation-for="WednesdayIsWeekend"></span>
                                </div>
                            </div>
                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="ThursdayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="ThursdayIsWeekend" />
                                    <span asp-validation-for="ThursdayIsWeekend"></span>
                                </div>
                            </div>
                            <div class="form-group row advanced-setting">
                                <div class="col-md-3">
                                    <nop-label asp-for="FridayIsWeekend" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="FridayIsWeekend" />
                                    <span asp-validation-for="FridayIsWeekend"></span>
                                </div>
                            </div>

                        </div>
                    </nop-card>
                </nop-cards>
            </div>
        </div>
    </section>
</form>


<form asp-controller="SalesForecasting" asp-action="TrainModel" method="post" id="train-form-id">
    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <nop-cards id="salesForcasting-cards">
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <input hidden type="submit" name="save" class="btn bg-primary" value="@T("Admin.SalesForecasting.Configure.TrainModel")" />
                        </div>
                    </div>
                </nop-cards>
            </div>
        </div>
    </section>
</form>


<script asp-location="Footer">
    $(document).ready(function () {
        $("#train-button-id").click(function (event) {
            event.preventDefault();
            $("#train-form-id").submit();
        });
    });
</script>