Plugins/NopStation.Plugin.Misc.Core/Controllers/Select2Controller.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Catalog;
using NopStation.Plugin.Misc.Core.Models;

namespace NopStation.Plugin.Misc.Core.Controllers
{
    public class Select2Controller : NopStationAdminController
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly IManufacturerService _manufacturerService;

        public Select2Controller(ICategoryService categoryService,
            IProductService productService,
            IManufacturerService manufacturerService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _manufacturerService = manufacturerService;
        }

        public async Task<IActionResult> Products(string q, int page = 1)
        {
            var products = await _productService.SearchProductsAsync(
                showHidden: true,
                keywords: q,
                pageIndex: page - 1,
                pageSize: 10);

            var response = new Select2ResponseModel();
            foreach (var product in products)
            {
                response.Results.Add(new Select2ResponseModel.Select2Item
                {
                    Id = product.Id,
                    Text = product.Name,
                });
            }

            response.Pagination.More = products.HasNextPage;

            return Json(response);
        }

        public async Task<IActionResult> Categories(string q, int page = 1)
        {
            var categories = await _categoryService.GetAllCategoriesAsync(
                showHidden: true,
                categoryName: q, 
                pageIndex: page - 1,
                pageSize: 10);

            var response = new Select2ResponseModel();
            foreach (var category in categories)
            {
                response.Results.Add(new Select2ResponseModel.Select2Item
                {
                    Id = category.Id,
                    Text = await _categoryService.GetFormattedBreadCrumbAsync(category),
                });
            }

            response.Pagination.More = categories.HasNextPage;

            return Json(response);
        }

        public async Task<IActionResult> Manufacturers(string q, int page = 1)
        {
            var manufacturers = await _manufacturerService.GetAllManufacturersAsync(
                showHidden: true,
                manufacturerName: q,
                pageIndex: page - 1,
                pageSize: 10);

            var response = new Select2ResponseModel();
            foreach (var manufacturer in manufacturers)
            {
                response.Results.Add(new Select2ResponseModel.Select2Item
                {
                    Id = manufacturer.Id,
                    Text = manufacturer.Name,
                });
            }

            response.Pagination.More = manufacturers.HasNextPage;

            return Json(response);
        }
    }
}

Plugins/NopStation.Plugin.Misc.Core/Views/Shared/EditorTemplates/Color.cshtml
@model string

<style type="text/css">
    .color-input {
        display: none;
    }

    .k-picker-wrap.k-state-default span.k-select {
        display: none;
    }

    .form-horizontal .k-textbox, .form-horizontal .k-colorpicker {
        width: auto !important;
    }

    .k-picker-wrap.k-state-default {
        padding-right: 0 !important;
        height: 31px;
        border-radius: 50%;
    }

    .k-colorpicker .k-selected-color, .k-picker-wrap.k-state-border-down .k-selected-color, .k-picker-wrap.k-state-focused {
        border-radius: 50%;
    }
</style>

@{
    var colorCode = Model;
    if (string.IsNullOrWhiteSpace(colorCode))
    {
        colorCode = "#000000";    
    }
}

<input type="color" id="@Html.IdForModel()Picker" value="@colorCode" />
<div class="color-input">
    <input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@colorCode" />
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#@Html.IdForModel()Picker").kendoColorPicker({
            buttons: false,
            change: function (e) {
                $("#@Html.IdForModel()").val(e.value);
            }
        });
    });
</script>

Plugins/NopStation.Plugin.Misc.Core/Views/Shared/EditorTemplates/Select2Category.cshtml
@model int
@inject Nop.Services.Catalog.ICategoryService categoryService 

<select class="form-control" data-placeholder="Search for a category" style="width: 100%" id="@Html.IdForModel()" name="@Html.NameForModel()">
    @if (Model > 0) 
    {
        var category = await categoryService.GetCategoryByIdAsync(Model);
        if (category != null && !category.Deleted)
        {
            <option value="@Model" selected="selected">@(await categoryService.GetFormattedBreadCrumbAsync(category))</option>
        }
    }
</select>

<script>
    $(document).ready(function () {
        $('#@Html.IdForModel()').select2({
            ajax: {
                url: '@(Url.Action("Categories", "Select2"))',
                dataType: 'json',
                data: function (params) {
                    var query = {
                        q: params.term,
                        page: params.page || 1
                    }
                    return query;
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;

                    return data;
                },
                placeholder: 'Search for a category',
                minimumInputLength: 1
            }
        });
    });
</script>

Plugins/NopStation.Plugin.Misc.Core/Views/Shared/EditorTemplates/Select2Manufacturer.cshtml
@model int
@inject Nop.Services.Catalog.IManufacturerService manufacturerService

<select class="form-control" data-placeholder="Search for a manufacturer" style="width: 100%" id="@Html.IdForModel()" name="@Html.NameForModel()">
    @if (Model > 0) 
    {
        var manufacturer = await manufacturerService.GetManufacturerByIdAsync(Model);
        if (manufacturer != null && !manufacturer.Deleted)
        {
            <option value="@Model" selected="selected">@manufacturer.Name</option>
        }
    }
</select>

<script>
    $(document).ready(function () {
        $('#@Html.IdForModel()').select2({
            ajax: {
                url: '@(Url.Action("Manufacturers", "Select2"))',
                dataType: 'json',
                data: function (params) {
                    var query = {
                        q: params.term,
                        page: params.page || 1
                    }
                    return query;
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;

                    return data;
                },
                minimumInputLength: 1
            }
        });
    });
</script>

Plugins/NopStation.Plugin.Misc.Core/Views/Shared/EditorTemplates/Select2Product.cshtml
@model int
@inject Nop.Services.Catalog.IProductService productService

<select class="form-control" data-placeholder="Search for a product" style="width: 100%" id="@Html.IdForModel()" name="@Html.NameForModel()">
    @if (Model > 0) 
    {
        var product = await productService.GetProductByIdAsync(Model);
        if (product != null && !product.Deleted)
        {
            <option value="@Model" selected="selected">@product.Name</option>
        }
    }
</select>

<script>
    $(document).ready(function () {
        $('#@Html.IdForModel()').select2({
            ajax: {
                url: '@(Url.Action("Products", "Select2"))',
                dataType: 'json',
                data: function (params) {
                    var query = {
                        q: params.term,
                        page: params.page || 1
                    }
                    return query;
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;

                    return data;
                },
                minimumInputLength: 1
            }
        });
    });
</script>

Plugins/NopStation.Plugin.Misc.Core/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToString("hh:mm tt"))"/>
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoTimePicker({
            popup: {
                position: "bottom right",
                origin: "top right"
            }
        });
    });
</script>

Plugins/NopStation.Plugin.Misc.Core/Views/Shared/EditorTemplates/TimeNullable.cshtml
@model DateTime?
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@(Model > DateTime.MinValue || Model.HasValue ? Model.Value.ToString("hh:mm tt") : null)" />
<script>
    $(document).ready(function () {
        $("#@Html.IdForModel()").kendoTimePicker({
            popup: {
                position: "bottom right",
                origin: "top right"
            }
        });
    });
</script>